function doAll() {
    firebase.auth().onAuthStateChanged(user => {
        if (user) {
            getBookmarks(user)
        } else {
            console.log("No user is signed in");
        }
    });
}
doAll();

document.getElementById("noBookmarkButton").addEventListener('click', function () {
    window.location.assign('main.html');
});

document.getElementById("noBookmarkMealButton").addEventListener('click', function () {
    window.location.assign('main.html');
});


function getBookmarks(user) {
    document.getElementById("noMealsMessage").style.display = "none";
    var currentUser = firebase.auth().currentUser;
    db.collection("users").doc(user.uid)
        .get()
        .then(userDoc => {

            document.getElementById("sortHighestRatingButton").addEventListener("click", function () {
                sortBookmarksByRating(currentUser, "highest");
            });

            document.getElementById("sortLowestRatingButton").addEventListener("click", function () {
                sortBookmarksByRating(currentUser, "lowest");
            });

            // Get the Array of bookmarks
            var bookmarks = userDoc.data().bookmarks;
            console.log(bookmarks);

            // Get pointer the new card template
            let mealTemplate = document.getElementById("mealTemplate");

            if (!bookmarks || bookmarks.length === 0) {
                document.getElementById("noBookmarksMessage").style.display = "block"; // Display the Jumbotron
                document.getElementById("meals-go-here").style.display = "none"; // Hide the meals container
                document.getElementById("mealTimeDropdown").style.display = "none";
                document.querySelector(".btn-group").style.display = "none";
                return;
            }

            document.getElementById("noBookmarksMessage").style.display = "none";
            document.getElementById("meals-go-here").style.display = "block";

            // Iterate through the ARRAY of bookmarked hikes (document ID's)


            bookmarks.forEach(thisMeal => {
                console.log(thisMeal);
                db.collection("meals")
                    .doc(thisMeal)
                    .get()
                    .then(doc => {
                        var docID = doc.id;  //this is the autogenerated ID of the document
                        var mealPoster = doc.data().name;
                        var image = doc.data().image;
                        var mealName = doc.data().mealTitle;
                        var mealType = doc.data().mealTime;
                        var update = doc.data().last_updated.toDate().toLocaleDateString();
                        var arating = doc.data().averagerating;
                        //clone the new card
                        let newmeal = mealTemplate.content.cloneNode(true);

                        //update title and some pertinant information
                        let imgEvent = newmeal.querySelector(".meal-img");
                        imgEvent.src = image;
                        newmeal.querySelector('a').href = "meal.html?docID=" + docID;
                        newmeal.querySelector(".card-title").innerHTML = mealName;
                        newmeal.querySelector(".card-text").innerHTML = mealType;
                        newmeal.querySelector(".update").innerHTML = update;
                        newmeal.querySelector(".rating-number").innerHTML = arating;
                        newmeal.querySelector(".card-poster").innerHTML = mealPoster;

                        // Assigning unique ID to the bookmark icon
                        // Attaching an onclick. Calling callback function (with meal's ID)
                        let bookmarkIcon = newmeal.querySelector("i");
                        if (bookmarkIcon) {
                            bookmarkIcon.id = 'save-' + docID;
                            bookmarkIcon.onclick = (function (mealID) {
                                return function () {
                                    toggleBookmark(mealID);
                                };
                            })(docID);
                        }

                        // Check if the meal is bookmarked by the current user
                        db.collection("users").doc(user.uid).get().then(userDoc => {
                            // get the username
                            let bookmarks = userDoc.data().bookmarks;
                            if (bookmarks.includes(docID)) {
                                if (bookmarkIcon) {
                                    bookmarkIcon.innerText = 'bookmark';
                                }

                            }
                        });
                        document.getElementById("meals-go-here").appendChild(newmeal);
                    });

            });

        })
}

function filterMealsByTimeAndBookmarks(mealTime) {
    // Clear the existing meals in the container
    document.getElementById("meals-go-here").innerHTML = "";
    document.getElementById("noMealsMessage").style.display = "none";

    var currentUser = firebase.auth().currentUser;

    // Get the current user
    firebase.auth().onAuthStateChanged(function (user) {
        if (user) {


            // Get the user's bookmarks
            db.collection("users").doc(user.uid)
                .get()
                .then(userDoc => {
                    var bookmarks = userDoc.data().bookmarks;

                    // Check if there are no bookmarks
                    if (!bookmarks || bookmarks.length === 0) {
                        document.getElementById("noBookmarksMessage").style.display = "block"; // Display the Jumbotron
                        document.getElementById("meals-go-here").style.display = "none"; // Hide the meals container
                        return;
                    }

                    document.getElementById("noBookmarksMessage").style.display = "none";
                    document.getElementById("meals-go-here").style.display = "block";

                    // Iterate through the ARRAY of bookmarked meals (document ID's)
                    bookmarks.forEach(thisMeal => {
                        // Query meals collection based on mealTime and bookmarks
                        db.collection("meals")
                            .doc(thisMeal)
                            .get()
                            .then(doc => {
                                if (doc.data().mealTime === mealTime) {
                                    var docID = doc.id; //this is the autogenerated ID of the document
                                    var mealPoster = doc.data().name;
                                    let image = doc.data().image;
                                    var mealName = doc.data().mealTitle;
                                    var mealType = doc.data().mealTime;
                                    var update = doc.data().last_updated.toDate().toLocaleDateString();
                                    var arating = doc.data().averagerating;

                                    // Clone the new card template
                                    let newmeal = mealTemplate.content.cloneNode(true);

                                    // Update title and some pertinent information
                                    let imgEvent = newmeal.querySelector(".meal-img");
                                    imgEvent.src = image;
                                    newmeal.querySelector('a').href = "meal.html?docID=" + docID;
                                    newmeal.querySelector(".card-title").innerHTML = mealName;
                                    newmeal.querySelector(".card-text").innerHTML = mealType;
                                    newmeal.querySelector(".update").innerHTML = update;
                                    newmeal.querySelector(".rating-number").innerHTML = arating;
                                    newmeal.querySelector(".card-poster").innerHTML = mealPoster;

                                    document.getElementById("noMealsMessage").style.display = "none";

                                    // Assigning unique ID to the bookmark icon
                                    // Attaching an onclick. Calling callback function (with meal's ID)
                                    let bookmarkIcon = newmeal.querySelector("i");
                                    if (bookmarkIcon) {
                                        bookmarkIcon.id = 'save-' + docID;
                                        bookmarkIcon.onclick = (function (mealID) {
                                            return function () {
                                                toggleBookmark(mealID);
                                            };
                                        })(docID);
                                    }

                                    // Check if the meal is bookmarked by the current user
                                    db.collection("users").doc(user.uid).get().then(userDoc => {
                                        // get the username
                                        let bookmarks = userDoc.data().bookmarks;
                                        if (bookmarks.includes(docID)) {
                                            if (bookmarkIcon) {
                                                bookmarkIcon.innerText = 'bookmark';
                                            }

                                        }
                                    });
                                    document.getElementById("meals-go-here").appendChild(newmeal);
                                }
                            })
                    });

                    if (document.getElementById("meals-go-here").childElementCount === 0) {
                        document.querySelector(".btn-group").style.display = "none";
                        document.getElementById("noMealsMessage").style.display = "block";
                    }
                })

        } else {
            console.log("Error, no user signed in");
        }
    });
}

// Example usage when the user selects a mealTime
document.getElementById("breakfast").addEventListener("click", function () {
    filterMealsByTimeAndBookmarks("Breakfast");
});

document.getElementById("lunch").addEventListener("click", function () {
    filterMealsByTimeAndBookmarks("Lunch");
});

document.getElementById("dinner").addEventListener("click", function () {
    filterMealsByTimeAndBookmarks("Dinner");
});

document.getElementById("snack").addEventListener("click", function () {
    filterMealsByTimeAndBookmarks("Snack");
});

document.getElementById("clearFilter").addEventListener("click", function () {
    refreshPage();
    document.getElementById("refresh").style.display = "";
});

function toggleDropdown() {
    var dropdown = document.getElementById("mealTimeDropdown");
    dropdown.classList.toggle("active");
}

function toggleBookmark(mealDocID) {
    var currentUser = firebase.auth().currentUser;
    var userDocRef = db.collection("users").doc(currentUser.uid);

    userDocRef.get()
        .then(function (doc) {
            if (doc.exists) {
                var isBookmarked = doc.data().bookmarks && doc.data().bookmarks.includes(mealDocID);

                if (isBookmarked) {
                    // If already bookmarked, remove it from the bookmarks array
                    return userDocRef.update({
                        bookmarks: firebase.firestore.FieldValue.arrayRemove(mealDocID)
                    })
                        .then(function () {
                            console.log("Bookmark has been removed for " + mealDocID);
                            var iconID = 'save-' + mealDocID;
                            document.getElementById(iconID).innerText = 'bookmark_border';
                            document.getElementById('bookmarkModalLabel').innerHTML = 'Bookmark Removed!';
                        })
                } else {
                    // If not bookmarked, add it to the bookmarks array
                    return userDocRef.update({
                        bookmarks: firebase.firestore.FieldValue.arrayUnion(mealDocID)
                    })
                        .then(function () {
                            console.log("Bookmark has been saved for " + mealDocID);
                            var iconID = 'save-' + mealDocID;
                            document.getElementById(iconID).innerText = 'bookmark';
                            document.getElementById('bookmarkModalLabel').innerHTML = 'Bookmark Added!';
                        })
                }
            }
        })
}

function refreshPage() {
    location.reload();
}

function sortBookmarksByRating(user, sortOrder) {
    document.getElementById("meals-go-here").innerHTML = ""; // Clear existing meals
    document.getElementById("noMealsMessage").style.display = "none";

    db.collection("users").doc(user.uid).get().then(userDoc => {
        var bookmarks = userDoc.data().bookmarks;

        if (!bookmarks || bookmarks.length === 0) {
            document.getElementById("noBookmarksMessage").style.display = "block";
            document.getElementById("meals-go-here").style.display = "none";
            return;
        }

        document.getElementById("noBookmarksMessage").style.display = "none";
        document.getElementById("meals-go-here").style.display = "block";

        // Get details for each bookmarked meal
        Promise.all(bookmarks.map(bookmark => {
            return db.collection("meals").doc(bookmark).get();
        })).then(bookmarkDocs => {
            // Sort bookmarks by averagerating
            bookmarkDocs.sort((a, b) => {
                const ratingA = a.data().averagerating || 0; // Use 0 if averagerating is undefined
                const ratingB = b.data().averagerating || 0;

                return sortOrder === "highest" ? ratingB - ratingA : ratingA - ratingB;
            });

            // Display sorted bookmarks
            bookmarkDocs.forEach(doc => {
                var docID = doc.id;
                var mealPoster = doc.data().name;
                var image = doc.data().image;
                var mealName = doc.data().mealTitle;
                var mealType = doc.data().mealTime;
                var update = doc.data().last_updated.toDate().toLocaleDateString();
                var arating = doc.data().averagerating;

                // Clone the new card template
                let newmeal = mealTemplate.content.cloneNode(true);

                // Update title and some pertinent information
                let imgEvent = newmeal.querySelector(".meal-img");
                imgEvent.src = image;
                newmeal.querySelector('a').href = "meal.html?docID=" + docID;
                newmeal.querySelector(".card-title").innerHTML = mealName;
                newmeal.querySelector(".card-text").innerHTML = mealType;
                newmeal.querySelector(".update").innerHTML = update;
                newmeal.querySelector(".rating-number").innerHTML = arating;
                newmeal.querySelector(".card-poster").innerHTML = mealPoster;

                // Assigning unique ID to the bookmark icon
                // Attaching an onclick. Calling callback function (with meal's ID)
                let bookmarkIcon = newmeal.querySelector("i");
                if (bookmarkIcon) {
                    bookmarkIcon.id = 'save-' + docID;
                    bookmarkIcon.onclick = (function (mealID) {
                        return function () {
                            toggleBookmark(mealID);
                        };
                    })(docID);
                }

                // Check if the meal is bookmarked by the current user
                db.collection("users").doc(user.uid).get().then(userDoc => {
                    // get the username
                    let bookmarks = userDoc.data().bookmarks;
                    if (bookmarks.includes(docID)) {
                        if (bookmarkIcon) {
                            bookmarkIcon.innerText = 'bookmark';
                        }
                    }
                });

                document.getElementById("meals-go-here").appendChild(newmeal);
            });
        });
    });
}



